version: '3.1'

services:

  mongo:
    image: mongo
    container_name: jin_mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mobile

  # mongoclient:
  #   image: mongoclient/mongoclient:latest
  #   container_name: jin_mongoclient
  #   hostname: mongoclient
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 3300:3000


 